// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace GildedRoseKata.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Gilded Rose Kata", Description=@"	- All items have a SellIn value which denotes the number of days we have to sell the item
	- All items have a Quality value which denotes how valuable the item is
	- At the end of each day our system lowers both values for every item

Pretty simple, right? Well this is where it gets interesting:

	- Once the sell by date has passed, Quality degrades twice as fast
	- The Quality of an item is never negative
	- ""Aged Brie"" actually increases in Quality the older it gets
	- The Quality of an item is never more than 50
	- ""Sulfuras"", being a legendary item, never has to be sold or decreases in Quality
	- ""Backstage passes"", like aged brie, increases in Quality as its SellIn value approaches;
	Quality increases by 2 when there are 10 days or less and by 3 when there are 5 days or less but
	Quality drops to 0 after the concert
Just for clarification, an item can never have its Quality increase above 50, however ""Sulfuras"" is a
legendary item and as such its Quality is 80 and it never alters.

We have recently signed a supplier of conjured items. This requires an update to our system:

	- ""Conjured"" items degrade in Quality twice as fast as normal items", SourceFile="Features\\GildedRose2.feature", SourceLine=0)]
    public partial class GildedRoseKataFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "GildedRose2.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Gilded Rose Kata", @"	- All items have a SellIn value which denotes the number of days we have to sell the item
	- All items have a Quality value which denotes how valuable the item is
	- At the end of each day our system lowers both values for every item

Pretty simple, right? Well this is where it gets interesting:

	- Once the sell by date has passed, Quality degrades twice as fast
	- The Quality of an item is never negative
	- ""Aged Brie"" actually increases in Quality the older it gets
	- The Quality of an item is never more than 50
	- ""Sulfuras"", being a legendary item, never has to be sold or decreases in Quality
	- ""Backstage passes"", like aged brie, increases in Quality as its SellIn value approaches;
	Quality increases by 2 when there are 10 days or less and by 3 when there are 5 days or less but
	Quality drops to 0 after the concert
Just for clarification, an item can never have its Quality increase above 50, however ""Sulfuras"" is a
legendary item and as such its Quality is 80 and it never alters.

We have recently signed a supplier of conjured items. This requires an update to our system:

	- ""Conjured"" items degrade in Quality twice as fast as normal items", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void QualityChangesEachDay(string name, string cq, string cs, string rq, string rs, string notes, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("name", name);
            argumentsOfScenario.Add("cq", cq);
            argumentsOfScenario.Add("cs", cs);
            argumentsOfScenario.Add("rq", rq);
            argumentsOfScenario.Add("rs", rs);
            argumentsOfScenario.Add("notes", notes);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Quality changes each day", null, tagsOfScenario, argumentsOfScenario);
#line 23
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 24
testRunner.Given(string.Format("item \"{0}\" with current Quality {1} and current SellIn {2}", name, cq, cs), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 25
testRunner.When("a day passes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 26
testRunner.Then(string.Format("item has revised Quality {0} and revised Sellin {1}", rq, rs), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Quality changes each day, Variant 0", SourceLine=28)]
        public virtual void QualityChangesEachDay_Variant0()
        {
#line 23
this.QualityChangesEachDay("Non-specific-item", "1", "1", "0", "0", "quality decrease", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Quality changes each day, Variant 1", SourceLine=28)]
        public virtual void QualityChangesEachDay_Variant1()
        {
#line 23
this.QualityChangesEachDay("Non-specific-item", "0", "1", "0", "0", "never below 0", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Quality changes each day, Variant 2", SourceLine=28)]
        public virtual void QualityChangesEachDay_Variant2()
        {
#line 23
this.QualityChangesEachDay("Non-specific-item", "4", "0", "2", "-1", "twice as fast", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Quality changes each day, Variant 3", SourceLine=28)]
        public virtual void QualityChangesEachDay_Variant3()
        {
#line 23
this.QualityChangesEachDay("Aged Brie", "4", "1", "5", "0", "increases", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Quality changes each day, Variant 4", SourceLine=28)]
        public virtual void QualityChangesEachDay_Variant4()
        {
#line 23
this.QualityChangesEachDay("Aged Brie", "4", "0", "6", "-1", "increases twice", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Quality changes each day, Variant 5", SourceLine=28)]
        public virtual void QualityChangesEachDay_Variant5()
        {
#line 23
this.QualityChangesEachDay("Aged Brie", "4", "-1", "6", "-2", "increases twice", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Quality changes each day, Variant 6", SourceLine=28)]
        public virtual void QualityChangesEachDay_Variant6()
        {
#line 23
this.QualityChangesEachDay("Aged Brie", "49", "-1", "50", "-2", "50 limit", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Quality changes each day, Variant 7", SourceLine=28)]
        public virtual void QualityChangesEachDay_Variant7()
        {
#line 23
this.QualityChangesEachDay("Aged Brie", "50", "-1", "50", "-2", "50 limit", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Quality changes each day, Variant 8", SourceLine=28)]
        public virtual void QualityChangesEachDay_Variant8()
        {
#line 23
this.QualityChangesEachDay("Sulfuras, Hand of Ragnaros", "80", "1", "80", "1", "never changes", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Quality changes each day, Variant 9", SourceLine=28)]
        public virtual void QualityChangesEachDay_Variant9()
        {
#line 23
this.QualityChangesEachDay("Backstage passes to a TAFKAL80ETC concert", "1", "11", "2", "10", "increase by 1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Quality changes each day, Variant 10", SourceLine=28)]
        public virtual void QualityChangesEachDay_Variant10()
        {
#line 23
this.QualityChangesEachDay("Backstage passes to a TAFKAL80ETC concert", "1", "10", "3", "9", "increase by 2", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Quality changes each day, Variant 11", SourceLine=28)]
        public virtual void QualityChangesEachDay_Variant11()
        {
#line 23
this.QualityChangesEachDay("Backstage passes to a TAFKAL80ETC concert", "1", "6", "3", "5", "increase by 2", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Quality changes each day, Variant 12", SourceLine=28)]
        public virtual void QualityChangesEachDay_Variant12()
        {
#line 23
this.QualityChangesEachDay("Backstage passes to a TAFKAL80ETC concert", "1", "5", "4", "4", "increase by 3", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Quality changes each day, Variant 13", SourceLine=28)]
        public virtual void QualityChangesEachDay_Variant13()
        {
#line 23
this.QualityChangesEachDay("Backstage passes to a TAFKAL80ETC concert", "1", "0", "0", "-1", "after concert", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Quality changes each day, Variant 14", SourceLine=28)]
        public virtual void QualityChangesEachDay_Variant14()
        {
#line 23
this.QualityChangesEachDay("Backstage passes to a TAFKAL80ETC concert", "50", "11", "50", "10", "50 limit", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Quality changes each day alternative", SourceLine=44)]
        public virtual void QualityChangesEachDayAlternative()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Quality changes each day alternative", null, tagsOfScenario, argumentsOfScenario);
#line 45
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "name",
                            "cq",
                            "cs",
                            "rq",
                            "rs",
                            "notes"});
                table1.AddRow(new string[] {
                            "Non-specific-item",
                            "1",
                            "1",
                            "0",
                            "0",
                            "quality decrease"});
                table1.AddRow(new string[] {
                            "Non-specific-item",
                            "0",
                            "1",
                            "0",
                            "0",
                            "never below 0"});
                table1.AddRow(new string[] {
                            "Non-specific-item",
                            "4",
                            "0",
                            "2",
                            "-1",
                            "twice as fast"});
                table1.AddRow(new string[] {
                            "Aged Brie",
                            "4",
                            "1",
                            "5",
                            "0",
                            "increases"});
                table1.AddRow(new string[] {
                            "Aged Brie",
                            "4",
                            "0",
                            "6",
                            "-1",
                            "increases twice"});
                table1.AddRow(new string[] {
                            "Aged Brie",
                            "4",
                            "-1",
                            "6",
                            "-2",
                            "increases twice"});
                table1.AddRow(new string[] {
                            "Aged Brie",
                            "49",
                            "-1",
                            "50",
                            "-2",
                            "50 limit"});
                table1.AddRow(new string[] {
                            "Aged Brie",
                            "50",
                            "-1",
                            "50",
                            "-2",
                            "50 limit"});
                table1.AddRow(new string[] {
                            "Sulfuras, Hand of Ragnaros",
                            "80",
                            "1",
                            "80",
                            "1",
                            "never changes"});
                table1.AddRow(new string[] {
                            "Backstage passes to a TAFKAL80ETC concert",
                            "1",
                            "11",
                            "2",
                            "10",
                            "increase by 1"});
                table1.AddRow(new string[] {
                            "Backstage passes to a TAFKAL80ETC concert",
                            "1",
                            "10",
                            "3",
                            "9",
                            "increase by 2"});
                table1.AddRow(new string[] {
                            "Backstage passes to a TAFKAL80ETC concert",
                            "1",
                            "6",
                            "3",
                            "5",
                            "increase by 2"});
                table1.AddRow(new string[] {
                            "Backstage passes to a TAFKAL80ETC concert",
                            "1",
                            "5",
                            "4",
                            "4",
                            "increase by 3"});
                table1.AddRow(new string[] {
                            "Backstage passes to a TAFKAL80ETC concert",
                            "1",
                            "0",
                            "0",
                            "-1",
                            "after concert"});
                table1.AddRow(new string[] {
                            "Backstage passes to a TAFKAL80ETC concert",
                            "50",
                            "11",
                            "50",
                            "10",
                            "50 limit"});
#line 48
testRunner.And("Quality changes after a day passes for specific items", ((string)(null)), table1, "* ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Quality changes each day for items (Type Scenario)", SourceLine=66)]
        public virtual void QualityChangesEachDayForItemsTypeScenario()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Quality changes each day for items (Type Scenario)", null, tagsOfScenario, argumentsOfScenario);
#line 67
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "name",
                            "type"});
                table2.AddRow(new string[] {
                            "Non-specific-item",
                            "NORMAL"});
                table2.AddRow(new string[] {
                            "Aged Brie",
                            "BRIE"});
                table2.AddRow(new string[] {
                            "Sulfuras, Hand of Ragnaros",
                            "LEGACY"});
                table2.AddRow(new string[] {
                            "Backstage passes to a TAFKAL80ETC concert",
                            "PASS"});
#line 68
testRunner.And("Quality change type for specific items", ((string)(null)), table2, "* ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("SellIn changes each day except for Sulfuras", SourceLine=74)]
        public virtual void SellInChangesEachDayExceptForSulfuras()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("SellIn changes each day except for Sulfuras", null, tagsOfScenario, argumentsOfScenario);
#line 75
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "type",
                            "cs",
                            "rs",
                            "notes"});
                table3.AddRow(new string[] {
                            "NORMAL",
                            "1",
                            "0",
                            "SellIn down by 1"});
                table3.AddRow(new string[] {
                            "NORMAL",
                            "-1",
                            "-2",
                            "Regardless of value"});
                table3.AddRow(new string[] {
                            "NORMAL",
                            "100",
                            "99",
                            "Is there a maximum SellIn?"});
                table3.AddRow(new string[] {
                            "LEGACY",
                            "1",
                            "1",
                            "SellIn never changes"});
#line 77
testRunner.And("SellIn changes after a day passes", ((string)(null)), table3, "* ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Quality changes each day for items (Change Scenario)", SourceLine=83)]
        public virtual void QualityChangesEachDayForItemsChangeScenario()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Quality changes each day for items (Change Scenario)", null, tagsOfScenario, argumentsOfScenario);
#line 84
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "type",
                            "cq",
                            "cs",
                            "rq",
                            "notes"});
                table4.AddRow(new string[] {
                            "NORMAL",
                            "1",
                            "1",
                            "0",
                            "quality decrease"});
                table4.AddRow(new string[] {
                            "NORMAL",
                            "0",
                            "1",
                            "0",
                            "never below 0"});
                table4.AddRow(new string[] {
                            "NORMAL",
                            "4",
                            "0",
                            "2",
                            "twice as fast"});
                table4.AddRow(new string[] {
                            "BRIE",
                            "4",
                            "1",
                            "5",
                            "increases"});
                table4.AddRow(new string[] {
                            "BRIE",
                            "4",
                            "0",
                            "6",
                            "increases twice"});
                table4.AddRow(new string[] {
                            "BRIE",
                            "4",
                            "-1",
                            "6",
                            "increases twice"});
                table4.AddRow(new string[] {
                            "BRIE",
                            "49",
                            "-1",
                            "50",
                            "50 limit"});
                table4.AddRow(new string[] {
                            "BRIE",
                            "50",
                            "-1",
                            "50",
                            "50 limit"});
                table4.AddRow(new string[] {
                            "UNCHANGED",
                            "80",
                            "1",
                            "80",
                            "never changes"});
                table4.AddRow(new string[] {
                            "PASS",
                            "1",
                            "11",
                            "2",
                            "increase by 1"});
                table4.AddRow(new string[] {
                            "PASS",
                            "1",
                            "10",
                            "3",
                            "increase by 2"});
                table4.AddRow(new string[] {
                            "PASS",
                            "1",
                            "6",
                            "3",
                            "increase by 2"});
                table4.AddRow(new string[] {
                            "PASS",
                            "1",
                            "5",
                            "4",
                            "increase by 3"});
                table4.AddRow(new string[] {
                            "PASS",
                            "1",
                            "0",
                            "0",
                            "after concert"});
                table4.AddRow(new string[] {
                            "PASS",
                            "50",
                            "11",
                            "50",
                            "50 limit"});
#line 85
testRunner.And("Quality changes after a day passes based on item type", ((string)(null)), table4, "* ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
